

services:
  postgres:
    env_file:
      - .env.docker
    hostname: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    env_file:
      - .env.docker
    hostname: redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

  web:
    env_file:
      - .env.docker
      - .flaskenv
    hostname: web
    depends_on:
      - postgres
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"


networks:
  default:
    name: backend
    driver: bridge

volumes:
  postgres_data: